proxy:
    build: ./containers/proxy
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
    ports:
        - "80:80"

redis:
    build: ./containers/redis
    privileged: true
    volumes:
        - ./containers/redis:/data
    ports:
        - "6379:6379"
    entrypoint: redis-server

web:
    build: ./containers/web
    environment:
        - VIRTUAL_HOST=meetup.inet
    links:
        - redis:redis.inet
    privileged: true
    volumes:
        - ./meetup-app:/src
    ports:
        - "80"
    entrypoint: /run.sh